### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [esong165/cse110-w21-group25#128]
**As a user of a pomodoro timer, I would like to:** be able to use the settings that I have selected even if I reopen the tab later.

**Additional Description:**
Store all settings in local storage, reload them on load, and remove the timer call that I added to utilize Firefox's auto save which Chromium doesn't have.

**Tasks**

- [ ] Save all settings to local storage
- [ ] Reload them on load
- [ ] Remove timer call
- [ ] Add tests for remembering
