### ISSUE TITLE
Timer functions

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#18]
**As a user, I would like to:** set a timer for 25, 10, or 5 minutes to use the Pomodoro technique.

**Additional Description:**
For our MVP, we will have 3 buttons that each set timers for their respective intervals.
Buttons should be disabled while the timer is running (aside from stop).
A sound should play when the timer reaches 0.

**Tasks**

- [ ] Implement timer with 3 timer intervals of 25, 10, 5 minutes
- [ ] Buttons aside from stop should be disabled 
- [ ] Have the timer play a sound when it reaches 0
- [ ] Implement unit tests for the timer functionality
- [ ] Timer passes unit tests
