### ISSUE TITLE
Add Countdown Timer

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#19]
**As a user of a pomodoro timer, I would like to:** 
Be able to run a timer that counts down from certain time intervals to 0.

**Additional Description:**
We need a timer with a basic countdown functionality based on the Date API. When the timer hits 0, there should be an alert notifying the user that the timer has finished running.

**Tasks**

- [x] Basic countdown timer using Date API
- [x] Countdown timer updates timer display
- [x] When timer hits 0, alert
- [x] Write unit tests to be run with Jest
