### ISSUE TITLE
TaskList

### ISSUE THREAD

**Issue by bananahbatman** [esong165/cse110-w21-group25#21]
**As a user of a pomodoro timer, I would like to:**
Have a Task 

**Additional Description:**
Implement Html tasklist. This will take the form of a popup, which will open when it is pressed. The tasklist will be a list of each task and the # of pomo's it is estimated to take. There will be an input option at the bottom of the list to add a new task. There will be a button beside each task to remove it. Clicking on a task will select it. A display above the timer will show the current task. A done button will remove the task from the list. 

**Tasks**

- [x] Implement Html tasklist in the form of a popup triggered by a button, that displays task name and the number of pomo's it will take. The popup will close when the button is clicked again. (I think using the summary html tag might be useful for this)
- [x] Add a remove button next to each task that will remove it from tasklist.
- [x] Add a create task button at the bottom of the task list and two inputs (text and number) representing task name and # pomos. Clicking the button will add task only if two inputs is provided, then both inputs will be cleared.
- [x] Displayed task name that will appear over the timer and display the currently selected task. If no task is selected it will be set to "Working". 
- [x] Done button that will remove the displayed task name from the task list.
- [x] Select a task option that will selects a task  when it's name or # of pomos is clicked and displays it on top of the timer.
- [x] Implement unit tests for the tasklist functionality
- [x] tasklist passes unit tests
