### ISSUE TITLE
Set timer intervals

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#22]
**As a user of a pomodoro timer, I would like to:** let the timer run for 5, 10, and 25 minute intervals.

**Additional Description:**
The timer should have the ability to run for 3 different intervals depending on the selected interval.
We should be able to change the 5 and 10 minute intervals later on (to an extent), so do not implement these as magic numbers.

**Tasks**

- [x] Add HTML for the timer to display it
- [x] Add initial timer interval to the countdown timer
- [x] Reflect the interval on the timer
- [x] Add ability to set timer to another interval using another function
- [x] Update the diagram on Miro
- [x] Write unit tests
- [x] Fix Jest integration with ES6 for unit tests to run
