### ISSUE TITLE
Add button to control timer

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#23]
**As a child/young student, I would like to:** have one button control the pomodoro cycle to streamline the user experience.

**Additional Description:** 
The app will have one button to start the task, fail the task during a session, and move on to the next part of the pomodoro cycle once the current one is over.

**Tasks**

- [x] Implement button to start/reset timer
- [x] Button states: start pomo, start short break, start long break
- [x] Button should have "fail task" states during the cycle
- [x] Pomodoro goes for long break during every 4th run of cycle
