### ISSUE TITLE
Integrate number of pomos taken into tasks

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#38]
**As a user of a pomodoro timer, I would like to:** know how many pomodoro cycles I have spent on a task.

**Additional Description:**
- Tasks should contain a field describing how many pomodoro cycles have been spent on that task.
- This field should be updated at the *end* of a cycle.
- This field will eventually be exported to stats.

**Tasks**

- [ ] Add a field describing the number of cycles spent on a task
- [ ] Field updates at end of a cycle
- [ ] Write unit tests
