### ISSUE TITLE
Implement Navigation Bar

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#45]
**As a child with a low attention span, I would like to:** see a navigation bar that takes me to each part of the app.

**Additional Description:**
- Nav bar will contain home/timer, tasklist, stats, settings/FAQ
- Current section (e.g. user on tasklist) will be highlighted
- User will be able to freely move between sections when not in a pomo session, tasklist/stats locked off during pomo session (exception when task is completed) 

**Tasks**

- [x] Implement navigation bar for moving between sections of the app
- [x] Current section is highlighted
- [x] Tasklist, stats are locked off while working (tasklist opens up when task is completed during work)
- [x] Implement E2E Tests
