### ISSUE TITLE
Dragging and dropping task items

### ISSUE THREAD

**Issue by DuckDuckWhaleUCSD** [esong165/cse110-w21-group25#50]
**As a user of a pomodoro timer, I would like to:** organize and order my task list by dragging and dropping them so that I don't have to worry about what to do next within a pomo and can automatically get my next task.

**Additional Description:** Allow dragging and dropping for reordering task items. Either drag the whole item or add an icon at the left to drag on. Make sure that it is stored properly and timer still takes task top to bottom.

**Tasks**

- [ ] Experiment with dragging and dropping, or find a library if it's too hard
- [ ] Implement dragging and dropping (with or without icon)
- [ ] Test and make sure it works with local storage
- [ ] Test and make sure it works with timer taking tasks
- [ ] Add unit tests if appropriate (if additional logic methods are introduced)
