### ISSUE TITLE
Tasks Track Current Pomos

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#51]
**As a procrastinator, I would like to:** see how many pomodoro cycles I have spent on each task.

**Tasks**

- [x] Add currPomos field to task-items
- [x] currPomos updates with each pomodoro cycle spent on a task
- [ ] Write tests for this feature
