### ISSUE TITLE
Animated Timer

### ISSUE THREAD

**Issue by esong165** [esong165/cse110-w21-group25#52]
**As a child, I would like to:** see an animated countdown timer that visually depletes as the timer counts down.

**Additional Description:**
Add an animated circle timer -- the timer will deplete by "shrinking" **clockwise** as the timer ticks down

**Tasks**

- [ ] Experiment with SVG rings/circles
- [ ] Implement circle timer that depletes with timer countdown
- [ ] Circle timer resets once the next part of a cycle is started (next session/break)
- [ ] Circle timer resets when user fails task
- [ ] Write tests as needed/if necessary
