### ISSUE TITLE
[BUG] Add highlighting to hover over elements or select

### ISSUE THREAD

**Issue by bananahbatman** [esong165/cse110-w21-group25#68]
**As a user of a pomodoro timer, I would like to:**

Have the following:
-Need to highlight select button when hover over task.
-Highlight the currently selected task.
-Need to highlight trash can button, when hover over trash can.
-Highlight selected navbar Icon (optional).

**Additional Description:**

**Tasks**

- [x] Need to highlight select button when hover over task.
- [x] Highlight the currently selected task.
- [x] Need to highlight trash can button, when hover over trash can.
- [x] Highlight selected navbar Icon (optional).
- [x] Add dynamic highlighting that will highlight different colors for different backgrounds.
- [x] Fix the trash can highlight
- [x] Add highlighting or icon change when hover over done button.
